### ISSUE TITLE
Locked database

### ISSUE THREAD

**Issue by Lucasv-github** [Dec4on/OPENSPY#5]
> The database seems to be locked, sometimes
> Should be replicable by using /find a few times
![bild](https://github.com/Dec4on/OPENSPY/assets/91936924/d6a36d02-c183-4ae3-b609-5c00392c5d5d)

**Comment by Dec4on** [comment]
I'll try to fix it

**Comment by Dec4on** [comment]
This probably happens because I have a database connection open in two different threading threads. I can't recreate the bug and I also have no idea how to fix it. I'll keep this issue open
